<a href="https://colab.research.google.com/github/Meirlen/DataScince/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from wordcloud import WordCloud, STOPWORDS
from nltk.corpus import stopwords
import nltk
import re
from string import punctuation
from matplotlib.pyplot import figure

In [44]:
df_marafon = pd.read_csv('/content/drive/MyDrive/upwork/marafon-chat-7k-messages.csv', sep = ';')
pd.set_option('display.max_columns', None)
df_marafon.shape

(6999, 26)

# EDA (Разведочный анализ данных)

In [45]:
headers = []
for i in range(df_marafon.shape[1]):
  headers.append(f'feat{i}')

df_marafon.columns = headers  
df_marafon.head(2)

,feat0,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat8,feat9,feat10,feat11,feat12,feat13,feat14,feat15,feat16,feat17,feat18,feat19,feat20,feat21,feat22,feat23,feat24,feat25
0,33478,2022-07-18 20:06:29.343,Натали,0,NaN,NaN,23212101,27977,32,32,26,chat185907,1.0,0,NaN,202717,marafon_bot_v1,185907,Viber,viber|1|9BXgxV3wSj/XnAOChxBs0A==|183803,183803,choice,subscriber,NaN,0,NaN
1,33477,2022-07-18 20:06:28.497,Натали,0,NaN,NaN,23212099,27977,32,32,26,chat185907,1.0,0,NaN,202717,marafon_bot_v1,185907,Viber,viber|1|9BXgxV3wSj/XnAOChxBs0A==|183803,183803,choice,subscriber,NaN,0,NaN

In [41]:
df_marafon.isnull().sum(axis = 0)

feat0        0
feat1        0
feat2        9
feat3        0
feat4     4445
feat5     1169
feat6        0
feat7        0
feat8     6891
feat9     6891
feat10       0
feat11       1
feat12       1
feat13       0
feat14    6999
feat15       0
feat16       1
feat17       0
feat18      53
feat19       1
feat20       0
feat21       1
feat22       1
feat23    6999
feat24       0
feat25    6999
dtype: int64

In [46]:
# удалим неинформативные признаки
df_marafon.drop(['feat25', 'feat23', 'feat14', 'feat14','feat8','feat9'], axis=1, inplace=True)
df_marafon.head(2)

,feat0,feat1,feat2,feat3,feat4,feat5,feat6,feat7,feat10,feat11,feat12,feat13,feat15,feat16,feat17,feat18,feat19,feat20,feat21,feat22,feat24
0,33478,2022-07-18 20:06:29.343,Натали,0,NaN,NaN,23212101,27977,26,chat185907,1.0,0,202717,marafon_bot_v1,185907,Viber,viber|1|9BXgxV3wSj/XnAOChxBs0A==|183803,183803,choice,subscriber,0
1,33477,2022-07-18 20:06:28.497,Натали,0,NaN,NaN,23212099,27977,26,chat185907,1.0,0,202717,marafon_bot_v1,185907,Viber,viber|1|9BXgxV3wSj/XnAOChxBs0A==|183803,183803,choice,subscriber,0

In [50]:
df_marafon.rename(columns = {'feat4':'UserType', 'feat2':'UserName', 'feat5':'text', 'feat1':'DateTime','feat11':'chat_id'}, inplace = True)
df_marafon = df_marafon[['UserName','UserType','text','chat_id','DateTime']]
df_marafon['UserType'] = df_marafon['UserType'].fillna('User')
df_marafon.loc[:100].head(2)

  UserName UserType text     chat_id                 DateTime
0   Натали     User  NaN  chat185907  2022-07-18 20:06:29.343
1   Натали     User  NaN  chat185907  2022-07-18 20:06:28.497

In [51]:
df_marafon['UserType'].value_counts()

User         4445
Kurator       670
Kurator7      507
Kurator6      483
Kurator55     235
Kurator21     224
Kurator5      182
Kurator56     121
Kurator38     116
Manager        16
Name: UserType, dtype: int64

In [52]:
df_marafon.head()

,UserName,UserType,text,chat_id,DateTime
0,Натали,User,NaN,chat185907,2022-07-18 20:06:29.343
1,Натали,User,NaN,chat185907,2022-07-18 20:06:28.497
2,Натали,User,NaN,chat185907,2022-07-18 20:06:18.923
3,Лена,User,"Добрий день. Так, я в безпеці, дякую, сподіваю...",chat43320,2022-07-18 13:18:55.353
4,Натали,User,Якщо можно я зроблю,chat185907,2022-07-18 11:54:02.817

In [53]:
df_marafon = df_marafon.iloc[::-1]
df_marafon.head(200)

,UserName,UserType,text,chat_id,DateTime
6998,Куратор Диана,Kurator,Ми вже відкрили вайбер чат.Приєднуйся: https:...,chat159591,2022-06-22 11:23:33.803
6997,ЛЮДМИЛА,User,"101,6",chat159591,2022-06-27 22:28:39.443
6996,ЛЮДМИЛА,User,За неделю -900,chat159591,2022-06-27 22:28:52.393
6995,Любов,User,Доброго вечора ??.,chat159537,2022-06-22 19:05:32.947
6994,Любов,User,NaN,chat159537,2022-06-22 19:05:47.883
...,...,...,...,...,...
6803,Анна Куратор,Kurator56,Света привіт.Чого косячиш?Голодна?Чи сумно?Чи ...,chat158643,2022-06-29 15:17:28.930
6802,Світлана,User,Анічка не знаю.Сама собі ворог.Якийсь внутрішн...,chat158643,2022-06-29 16:20:18.380
6801,Світлана,User,"Хвилююсь,а організм начинає запасатись .Тривога ?",chat158643,2022-06-29 16:20:53.210
6800,Анна Куратор,Kurator56,Порушення режиму немає? Все по меню?,chat158643,2022-06-29 16:41:10.383
6799,Світлана,User,В цьому і косяки.,chat158643,2022-06-29 19:38:41.073

## Bigrams

In [ ]:
!pip install pymorphy2

In [ ]:
# download stopwords corpus, you need to run it once
import nltk
nltk.download("stopwords")

from nltk.corpus import stopwords
import pymorphy2
from string import punctuation

In [56]:
print(stopwords.fileids()) # К сожалению в nltk нет поддержки русского языка но мы 
# можем создать свой кастомный корпус слов для украинского или можно найти другие источники

['arabic', 'azerbaijani', 'basque', 'bengali', 'catalan', 'chinese', 'danish', 'dutch', 'english', 'finnish', 'french', 'german', 'greek', 'hebrew', 'hinglish', 'hungarian', 'indonesian', 'italian', 'kazakh', 'nepali', 'norwegian', 'portuguese', 'romanian', 'russian', 'slovene', 'spanish', 'swedish', 'tajik', 'turkish']

In [57]:
#Create lemmatizer and stopwords list
morph = pymorphy2.MorphAnalyzer()
russian_stopwords = stopwords.words("russian")

In [58]:
from collections import defaultdict

In [61]:
def generate_ngrams(text, n_gram=1):
    text = str(text)
    tokens1 = [token for token in text.lower().split(' ') if token != '' if token not in russian_stopwords]
    tokens2 =[]
    for token in tokens1:
        token = morph.parse(token)[0].normal_form
        token = token.translate(str.maketrans('', '', punctuation))
        tokens2.append(token)
    ngrams = zip(*[tokens2[i:] for i in range(n_gram)])
    return [' '.join(ngram) for ngram in ngrams]

In [62]:
def generate_patterns(n_gram=2):
  alem_bigrams = defaultdict(int)

  for tweet in df_marafon['text']:
      for word in generate_ngrams(tweet,n_gram):
          alem_bigrams[word] += 1

  alem_bigrams = pd.DataFrame(sorted(alem_bigrams.items(), key=lambda x: x[1])[::-1])
  return generate_patterns(n_gram=2)

In [63]:
generate_patterns(2)

KeyboardInterrupt: ignored

# Разметка данных (Intent & entity)

In [ ]:
# После того как изучили данные можем приступить к разметке
# Нужно определить все намеренийя пользователя а также разметить  именованных сущностей :
# давайие рассмотрим такой пример:

### User
 Добрий ранок! Ось мої
результати за минулий тиждень:
Вага - 200 Груди 0 Талія - 0
Живіт - 1 Бедра - 1 Нога 0 Рука

intent = greet+report  entity = entity_report_count{Вага - 200},{Груди 0 - 200},{Талія - 0},{Живіт - 1},{Нога - 0},

Клиент здоровается передает отчет greet+report

### Kurator21
 Доброго дня, Ірочка. Сьогодні
хороший мінус.
 Ви ще не оплачували наступний
марафон? Не забудьте скинути
мені квитанцію.

Размечать ответы куратора не будем

### Kurator21

 Я сплатила ще вчора і одразу
Вам скинула, але ви мабуть не
бачили. Я зараз скину квитанцію
ще раз.
Ось, 768 грн. за два марафона
Оплачено 30.06

intent = customer_paid  entity = date{вчора}, money = {768 грн.}, date = {30.06}

### User
 Дякую!

intent = greet

In [26]:
df_marafon_clear_reversed.shape

(6999, 5)

In [27]:
df_marafon_clear_reversed.head(1000)

,UserName,UserType,text,chat_id,DateTime
6998,Куратор Диана,Kurator,Ми вже відкрили вайбер чат.Приєднуйся: https:...,chat159591,2022-06-22 11:23:33.803
6997,ЛЮДМИЛА,User,"101,6",chat159591,2022-06-27 22:28:39.443
6996,ЛЮДМИЛА,User,За неделю -900,chat159591,2022-06-27 22:28:52.393
6995,Любов,User,Доброго вечора ??.,chat159537,2022-06-22 19:05:32.947
6994,Любов,User,NaN,chat159537,2022-06-22 19:05:47.883
...,...,...,...,...,...
6003,Татьяна,User,Хотіла собі зберегти та випадково Вам закинула.,chat137415,2022-06-28 19:46:46.567
6002,Татьяна,User,Вибачте,chat137415,2022-06-28 19:46:59.873
6001,Куратор Диана,Kurator,Нічого все добре),chat137415,2022-06-28 19:49:06.973
6000,Татьяна,User,Доброго ранку.Сьогодні +0,chat137415,2022-06-29 08:28:38.910
5999,Куратор Диана,Kurator,"Доброго ранку, Танічка все добре, молодчинка, ...",chat137415,2022-06-29 10:48:06.403

In [64]:
# chat_id_flag = None
# for index, row in df_marafon_clear_reversed.iterrows():
#       chat_id = row[3]
#       user_type = row[1]
#       text = row[2]
#       if chat_id != chat_id_flag:
#          print(f'{chat_id}\n--------NEW CONVERSTATION---------')
#       print(user_type,'\n',text)
#       chat_id_flag = chat_id

In [65]:
# df_marafon_clear_reversed['chat_id'].unique().shape

In [ ]:
# П